    spring.application.name=ticketproject
        #spring.datasource.url=jdbc:mysql://localhost:3306/ticketdatabase?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        spring.datasource.url=jdbc:mysql://host.docker.internal:3306/ticketdatabase?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        spring.datasource.username=root
        spring.datasource.password=
        server.port=8091
        spring.jpa.show-sql=true
        spring.jpa.hibernate.ddl-auto=update
   # spring.config.import=optional:configserver:

    # Eureka
        eureka.client.register-with-eureka=true
        eureka.client.service-url.defaultZone=http://containereureka:8761/eureka/

# Spring RabbitMQ
#spring.rabbitmq.host=localhost
spring.rabbitmq.host=host.docker.internal
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# CONFIG SERVER
spring.cloud.config.enabled=true
#spring.config.import=optional:configserver:http://localhost:8888
spring.config.import=optional:configserver:http://containerconfig:8888

welcome.message= Welcome to ticket ms
management.endpoints.web.exposure.include=*

# Keycloak
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/Eventy_Realm
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://host.docker.internal:8080/realms/Eventy_Realm
